### ISSUE TITLE
GLTF scenes using KTX images are out of spec

### ISSUE THREAD

**Issue by jherico** [KhronosGroup/Vulkan-Samples-Assets#2]
The GLTF scenes are referencing KTX files which isn't supported by the spec, and no extension is specified that would allow it.  Third-party libraries may not be able to render the content.

**Comment by wasimabbas-arm** [comment]
This is an informed decision. We are not expecting these assets to be used by Third-party libraries. They are only suppose to work with our samples repo. For generic samples please use the GLTF Samples repo from khronos.

**Comment by jherico** [comment]
At the very least it would make sense to make up an extension name and then add it to the required extensions field of the file so that someone who tries to open the file in another app gets a reasonable error condition.

**Comment by wasimabbas-arm** [comment]
Yea that sounds reasonable. Submit a PR?
